
import { fetchGuts } from "./guts";

export async function fetchFeats(): Promise<Document> {
    let url = 'https://www.aidedd.org/feat/list.php';
    return fetchGuts(url, featureNames);
}

const featureNames = [
		'ability-score-improvement',
		'actor',
		'alert',
		'archery',
		'athlete',
		'blind-fighting',
		'boon-of-combat-prowess',
		'boon-of-dimensional-travel',
		'boon-of-energy-resistance',
		'boon-of-fate',
		'boon-of-fortitude',
		'boon-of-irresistible-offense',
		'boon-of-recovery',
		'boon-of-skill',
		'boon-of-speed',
		'boon-of-spell-recall',
		'boon-of-the-night-spirit',
		'boon-of-truesight',
		'charger',
		'chef',
		'crafter',
		'crossbow-expert',
		'crusher',
		'defense',
		'defensive-duelist',
		'dual-wielder',
		'dueling',
		'durable',
		'elemental-adept',
		'fey-touched',
		'grappler',
		'great-weapon-fighting',
		'great-weapon-master',
		'healer',
		'heavily-armored',
		'heavy-armor-master',
		'inspiring-leader',
		'interception',
		'keen-mind',
		'lightly-armored',
		'lucky',
		'mage-slayer',
		'magic-initiate',
		'martial-weapon-training',
		'medium-armor-master',
		'moderately-armored',
		'mounted-combatant',
		'musician',
		'observant',
		'piercer',
		'poisoner',
		'polearm-master',
		'protection',
		'resilient',
		'ritual-caster',
		'savage-attacker',
		'sentinel',
		'shadow-touched',
		'sharpshooter',
		'shield-master',
		'skill-expert',
		'skilled',
		'skulker',
		'slasher',
		'speedy',
		'spell-sniper',
		'tavern-brawler',
		'telekinetic',
		'telepathic',
		'thrown-weapon-fighting',
		'tough',
		'two-weapon-fighting',
		'unarmed-fighting',
		'war-caster',
		'weapon-master'
	];